=== Aviator-Coding/c-_development_assignments/CSH10B - LINQ-Konzepte/Lektion-04/Box.dtd
<!ELEMENT box (card)+>
<!ELEMENT card (keyword+, abstract?, content*, source?, createDate, date?)>
<!ELEMENT keyword (#PCDATA)>
<!ELEMENT abstract (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT createDate (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST card subject CDATA #IMPLIED>
<!ATTLIST content type (titel | text | quote | code | url | image) "text">

=== Aviator-Coding/c-_development_assignments/CSH10B - LINQ-Konzepte/Lektion-04/Box.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE box SYSTEM "Box.dtd">
<!-- erste Karte -->
<box>
<card subject="XML">
<keyword>DTD</keyword>
<keyword>Wikipedia</keyword>
<abstract>Wie erstellt man eine DTD?</abstract>
<content type="titel">Erst Struktur planen, dann umsetzen</content>
<content type="text">Nicht immer reicht eine Anleitung aus, die in Wikipedia steht:</content>
<content type="quote">Eine Dokumenttypdefinition (englisch Document Type Definition, DTD, auch Schema-Definition oder DOCTYPE) ist ein Satz an Regeln, der benutzt wird, um Dokumente eines bestimmten Typs zu deklarieren.</content>
<content type="url">http://de.wikipedia.org/wiki/ Dokumenttypdefinition</content>
<source>Web</source>
<createDate>20.05.2010</createDate>
<date>20.05.2010</date>
</card>
</box>
